import { supabase } from "@/integrations/supabase/client";
import type { TablesInsert } from "@/integrations/supabase/types";
import { Enums } from "@/integrations/supabase/types";

type UserRole = Enums<"user_role">;

export const signUpUser = async (email: string, password: string) => {
  console.log("Attempting to sign up user with email:", email);
  try {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${window.location.origin}/admin`,
      },
    });

    if (error) {
      console.error("Sign up error:", error);
      
      // Check for rate limit directly from the error response
      if (error.status === 429) {
        throw new Error("You've reached the maximum number of registration attempts. Please wait a few minutes before trying again.");
      }

      // Handle already registered users
      if (error.message?.includes('already registered')) {
        throw new Error("This email is already registered. Please try logging in instead.");
      }

      throw error;
    }

    console.log("Sign up successful:", data);
    return data;
  } catch (error: any) {
    console.error("Sign up error:", error);
    
    // Check if it's our custom error message
    if (error.message?.includes('maximum number of registration attempts') ||
        error.message?.includes('already registered')) {
      throw error;
    }

    // For unexpected errors, throw a generic message
    throw new Error("Registration failed. Please try again later.");
  }
};

export const createUserProfile = async (userId: string, email: string) => {
  console.log("Creating user profile for:", userId);
  
  const { data: { session }, error: sessionError } = await supabase.auth.getSession();
  
  if (sessionError || !session) {
    console.error("Session error:", sessionError);
    throw new Error("No valid session found");
  }

  const profileData: TablesInsert<'profiles'> = {
    id: userId,
    user_id: userId,
    email,
    role: 'member' as UserRole,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  const { data, error } = await supabase
    .from('profiles')
    .insert(profileData)
    .select()
    .single();

  if (error) {
    console.error("Profile creation error:", error);
    throw error;
  }

  console.log("Profile created successfully:", data);
  return data;
};

export const createMember = async (memberData: any, collectorId: string) => {
  console.log("Creating member with data:", { memberData, collectorId });
  
  const memberObject: TablesInsert<'members'> = {
    collector_id: collectorId,
    full_name: memberData.fullName,
    email: memberData.email,
    phone: memberData.mobile,
    address: memberData.address,
    town: memberData.town,
    postcode: memberData.postCode,
    date_of_birth: memberData.dob,
    gender: memberData.gender,
    marital_status: memberData.maritalStatus,
    status: 'pending',
    profile_updated: true,
    member_number: '', // This will be auto-generated by the database trigger
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  try {
    const { data, error } = await supabase
      .from('members')
      .insert(memberObject)
      .select()
      .single();

    if (error) {
      console.error("Member creation error:", error);
      throw error;
    }

    console.log("Member created successfully:", data);
    return data;
  } catch (error) {
    console.error("Error creating member:", error);
    throw error;
  }
};

export const createRegistration = async (memberId: string) => {
  console.log("Creating registration for member:", memberId);
  
  try {
    const { data, error } = await supabase
      .from('registrations')
      .insert({
        member_id: memberId,
        status: 'pending',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      })
      .select()
      .single();

    if (error) {
      console.error("Registration creation error:", error);
      throw error;
    }

    console.log("Registration created successfully:", data);
    return data;
  } catch (error) {
    console.error("Error creating registration:", error);
    throw error;
  }
};

export const updateMemberProfile = async (memberId: string, profileData: any) => {
  console.log("Updating member profile:", { memberId, profileData });

  try {
    const { data, error } = await supabase
      .from('members')
      .update({
        full_name: profileData.fullName,
        email: profileData.email,
        phone: profileData.mobile,
        address: profileData.address,
        town: profileData.town,
        postcode: profileData.postCode,
        date_of_birth: profileData.dob,
        gender: profileData.gender,
        marital_status: profileData.maritalStatus,
        profile_updated: true,
        updated_at: new Date().toISOString()
      })
      .eq('id', memberId)
      .select()
      .single();

    if (error) {
      console.error("Profile update error:", error);
      throw error;
    }

    console.log("Profile updated successfully:", data);
    return data;
  } catch (error) {
    console.error("Error updating profile:", error);
    throw error;
  }
};